DROP TABLE if exists public.hits CASCADE;

create table if not exists hits (
  id BIGINT generated by default as identity primary key,
  app VARCHAR(255) not null,
  uri VARCHAR(512) not null,
  ip VARCHAR(16) not null,
  hit_time TIMESTAMP without TIME zone not null
);